import Foundation

/// Generates the preview binary source files and Package.swift.
public struct PreviewRegistryGenerator {
    let entries: [PreviewEntry]
    let outputDir: String       // e.g., /path/to/project/.sparrow/preview
    let projectRoot: String

    public init(entries: [PreviewEntry], outputDir: String, projectRoot: String) {
        self.entries = entries
        self.outputDir = outputDir
        self.projectRoot = projectRoot
    }

    /// Generate all files needed for the preview binary.
    public func generate() throws {
        let fm = FileManager.default
        let sourcesDir = outputDir + "/Sources"

        // Clean and recreate Sources directory
        if fm.fileExists(atPath: sourcesDir) {
            try fm.removeItem(atPath: sourcesDir)
        }
        try fm.createDirectory(atPath: sourcesDir, withIntermediateDirectories: true)

        // Symlink user source files (excluding @main files)
        try symlinkUserSources(to: sourcesDir)

        // Generate registry
        let registrySource = generateRegistry()
        try registrySource.write(
            toFile: sourcesDir + "/_PreviewRegistry.swift",
            atomically: true,
            encoding: .utf8
        )

        // Generate main entry point
        let mainSource = generateMain()
        try mainSource.write(
            toFile: sourcesDir + "/_PreviewMain.swift",
            atomically: true,
            encoding: .utf8
        )

        // Generate Package.swift
        let packageSource = try generatePackage()
        try packageSource.write(
            toFile: outputDir + "/Package.swift",
            atomically: true,
            encoding: .utf8
        )
    }

    // MARK: - Source file symlinking

    private func symlinkUserSources(to targetDir: String) throws {
        let fm = FileManager.default
        let userSourcesDir = projectRoot + "/Sources"

        guard let enumerator = fm.enumerator(atPath: userSourcesDir) else { return }

        while let file = enumerator.nextObject() as? String {
            guard file.hasSuffix(".swift") else { continue }

            let fullPath = userSourcesDir + "/" + file
            let contents = (try? String(contentsOfFile: fullPath, encoding: .utf8)) ?? ""

            // Skip files with @main — the preview binary has its own entry point
            if contents.contains("@main") { continue }

            // Flatten directory structure into the target directory
            let linkName = file.replacingOccurrences(of: "/", with: "_")
            let linkPath = targetDir + "/" + linkName

            // Remove existing symlink if present
            if fm.fileExists(atPath: linkPath) {
                try fm.removeItem(atPath: linkPath)
            }

            try fm.createSymbolicLink(atPath: linkPath, withDestinationPath: fullPath)
        }
    }

    // MARK: - Code generation

    private func generateRegistry() -> String {
        let imports = "import Sparrow"

        let typeRefs = entries.map { entry in
            "            _SparrowPreview_\(entry.hashId).self,"
        }.joined(separator: "\n")

        return """
        // Auto-generated by `sparrow preview`. Do not edit.
        \(imports)

        enum _PreviewRegistry {
            static func all() -> [any SparrowPreview.Type] {
                [
        \(typeRefs)
                ]
            }
        }
        """
    }

    private func generateMain() -> String {
        """
        // Auto-generated by `sparrow preview`. Do not edit.
        import Sparrow
        import Foundation

        @main
        struct PreviewApp {
            static func main() async throws {
                let port = Int(ProcessInfo.processInfo.environment["SPARROW_PREVIEW_PORT"] ?? "5457") ?? 5457
                let server = PreviewServer(port: port)
                try await server.run(previews: _PreviewRegistry.all())
            }
        }
        """
    }

    private func generatePackage() throws -> String {
        // Extract the Sparrow dependency from the user's Package.swift so we can
        // replicate it. The preview runner compiles user source files directly
        // (via symlinks) and only needs Sparrow as a dependency.
        let userPackagePath = projectRoot + "/Package.swift"
        let userPackageContents = try String(contentsOfFile: userPackagePath, encoding: .utf8)

        let sparrowDep: String
        let packageName: String

        // Try to find a path-based dependency containing "sparrow" (local dev)
        let pathPattern = #"\.package\(path:\s*"([^"]+)"[^)]*\)"#
        let urlPattern = #"\.package\(url:\s*"([^"]*sparrow[^"]*)"[^)]*\)"#

        if let regex = try? NSRegularExpression(pattern: pathPattern),
           let match = regex.firstMatch(in: userPackageContents, range: NSRange(userPackageContents.startIndex..., in: userPackageContents)),
           let fullRange = Range(match.range, in: userPackageContents),
           let pathRange = Range(match.range(at: 1), in: userPackageContents) {
            let path = String(userPackageContents[pathRange])
            // Use the same absolute path — works from any Package.swift location
            sparrowDep = String(userPackageContents[fullRange])
            packageName = URL(fileURLWithPath: path).lastPathComponent
        } else if let regex = try? NSRegularExpression(pattern: urlPattern),
                  let match = regex.firstMatch(in: userPackageContents, range: NSRange(userPackageContents.startIndex..., in: userPackageContents)),
                  let fullRange = Range(match.range, in: userPackageContents),
                  let urlRange = Range(match.range(at: 1), in: userPackageContents) {
            // URL-based dependency — replicate it exactly
            sparrowDep = String(userPackageContents[fullRange])
            let urlString = String(userPackageContents[urlRange])
            // Package name from URL: last path component minus .git
            let lastComponent = URL(string: urlString)?.lastPathComponent ?? "sparrow"
            packageName = lastComponent.hasSuffix(".git")
                ? String(lastComponent.dropLast(4))
                : lastComponent
        } else {
            // Fallback: assume the user's project IS a Sparrow project
            // and the preview runner can depend on it directly
            sparrowDep = ".package(path: \"../../\")"
            packageName = "sparrow"
        }

        return """
        // swift-tools-version: 6.2
        // Auto-generated by `sparrow preview`. Do not edit.
        import PackageDescription

        let package = Package(
            name: "SparrowPreviewRunner",
            platforms: [.macOS(.v15)],
            dependencies: [
                \(sparrowDep),
            ],
            targets: [
                .executableTarget(
                    name: "SparrowPreviewRunner",
                    dependencies: [
                        .product(name: "Sparrow", package: "\(packageName)"),
                    ],
                    path: "Sources"
                ),
            ]
        )
        """
    }
}
